steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '-t',
           'us-central1-docker.pkg.dev/scientific-host-415721/cloud-run-source-deploy/my-app:${SHORT_SHA}',
           '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'us-central1-docker.pkg.dev/scientific-host-415721/cloud-run-source-deploy/my-app:${SHORT_SHA}']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/cloud-run'
    args: ['deploy',
           '--image',
           'us-central1-docker.pkg.dev/scientific-host-415721/cloud-run-source-deploy/my-app:${SHORT_SHA}',
           '--platform',
           'gcr.io/cloud-run/runtime-v2',
           '--region',
           'us-central1',
           '--allow-unauthenticated',  # Replace with appropriate authentication strategy
           '--service',
           'my-app']

options:
  logging: CLOUD_LOGGING_ONLY

# Store images in Google Artifact Registry
#images:
#  - us-central1-docker.pkg.dev/scientific-host-415721/cloud-run-source-deploy/my-app:${SHORT_SHA}