steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker:latest'
    args: ['build',
           '-t',
           'us-central1-docker.pkg.dev/scientific-host-415721/cloud-run-source-deploy/my-app:latest',
           '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'us-central1-docker.pkg.dev/scientific-host-415721/cloud-run-source-deploy/my-app:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/cloud-run'
    args: ['run',
           'deploy',
           '--image',
           'us-central1-docker.pkg.dev/scientific-host-415721/cloud-run-source-deploy/my-app:latest',
           '--platform',
           'gcr.io/cloud-run/runtime-v2',
           '--region',
           'us-central1']

options:
  logging: CLOUD_LOGGING_ONLY

# Store images in Google Artifact Registry
images: [us-central1-docker.pkg.dev/scientific-host-415721/cloud-run-source-deploy/my-app:latest]